version: '3'
services:
 crudapp:
  build: .
  ports:
  - "3000:3000"
  environment:
  - MONGODB_URI=mondodb://localhost:27017/mydb
  depends_on:
  - db
 db:
  image: mongo:latest
  volumes:
  - db_data:/data/db
  ports:
  - "27017:27017"
volumes:
 db_data: